name: AppConfiguration-JavaScriptImporter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      run: npm install -g pnpm

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Rush Update
      run: node common/scripts/install-run-rush.js update
    
    - name: Rush Install
      run: node common/scripts/install-run-rush.js install

    - name: Check Eslint format
      run: node common/scripts/install-run-rush.js check-format --verbose

    - name: Run Build
      run: node common/scripts/install-run-rush.js build

    - name: Run Tests
      run: node common/scripts/install-run-rush.js test --verbose

    - name: Remove dependencies
      run: node common/scripts/install-run-rush.js purge  