name: AppConfiguration-JavaScriptImporter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      run: npm install -g pnpm

    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version:  '18.x'

    - name: Rush Update
      run: node common/scripts/install-run-rush.js update
    
    - name: Rush Install
      run: node common/scripts/install-run-rush.js install

    - name: Check Eslint format
      run: node common/scripts/install-run-rush.js check-format --verbose

    - name: Run Build
      run: node common/scripts/install-run-rush.js build

    - name: Run Tests
      run: node common/scripts/install-run-rush.js test --verbose

    - name: Remove dependencies
      run: node common/scripts/install-run-rush.js purge  